services:
  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    env_file: .env
    volumes:
      - influx-data:/var/lib/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_ADMIN_USER}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_ADMIN_TOKEN}

  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    command: mosquitto -c /mosquitto-no-auth.conf

  api:
    build: ./api
    env_file: .env
    depends_on:
      - influxdb
      - mosquitto
    ports:
      - "8000:8000"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883

  # grafana:
  #   image: grafana/grafana:10.4.2
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - grafana-data:/var/lib/grafana
  #   depends_on:
  #     - influxdb

volumes:
  influx-data:
  grafana-data:
